DROP DATABASE IF EXISTS OBJAVAESC;

CREATE DATABASE OBJAVAESC;

USE OBJAVAESC;

CREATE TABLE EMPRESA (
    RUT BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    TELEFONO INT NOT NULL,
    ACTIVO BIT NOT NULL);
    
CREATE TABLE ASPIRANTE (
    CI BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    EDAD INT NOT NULL,
    ACTIVO BIT NOT NULL);
    
CREATE TABLE OFERTA (
    IDOFERTA INT PRIMARY KEY AUTO_INCREMENT,
    CARGO VARCHAR(50) NOT NULL,
    TITULO VARCHAR(50) NOT NULL,
    DESCRIPCIONCARGO VARCHAR(50) NOT NULL,
    DESCRIPCIONREQUICITOS VARCHAR(50) NOT NULL,
    VACANTES INT NOT NULL,
    RUT BIGINT NOT NULL,
    CI BIGINT NOT NULL,
    ACTIVA BIT NOT NULL,
    FOREIGN KEY (RUT) REFERENCES EMPRESA(RUT),
    FOREIGN KEY (CI) REFERENCES ASPIRANTE(CI));

CREATE TABLE ENTREVISTA (
    IDENTREVISTA INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATETIME NOT NULL,
    RESULTAD0 VARCHAR(50) NOT NULL,
    IDOFERTA INT NOT NULL,
    CI BIGINT NOT NULL,
    FOREIGN KEY (IDOFERTA) REFERENCES OFERTA(IDOFERTA));
    
CREATE TABLE CONTRATO (
    IDCONTRATO INT PRIMARY KEY AUTO_INCREMENT,
    IDENTREVISTA INT NOT NULL,
    IDEOFERTA INT NOT NULL,
    FECHA DATETIME NOT NULL,
    SUELDO INT NOT NULL,
    FOREIGN KEY (IDENTREVISTA) REFERENCES ENTREVISTA(IDENTREVISTA),
    FOREIGN KEY (IDEOFERTA) REFERENCES OFERTA(IDEOFERTA));